repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 24.4.2  # Versión 2024 estable
    hooks:
    -   id: black
        language_version: python3.10 # Fuerza la versión de tu proyecto

-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args: [--max-line-length=88, --extend-ignore=E203]

-   repo: https://github.com/pycqa/pylint
    rev: v4.0.5
    hooks:
    -   id: pylint
        args: [
                    "--rcfile=.pylintrc",         # Archivo de configuración
                    "--fail-under=9.0",           # ¡Aquí está la magia!
                    "--msg-template='{path}:{line}:{column}: {msg_id}({symbol}) {msg}'"
                ]
